config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  root'users#index'
  
  
  post 'top/login'
  get 'top/logout'
  get 'top/login'
  get 'top/main'
  
  resources :tweets
  post '/tweets/new',to:'tweets#new'
  
  resources :likes
  get 'likes/create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes
    has_many :like_users, through: :likes ,source: :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tweets
    has_many :likes
    has_many :like_tweets, through: :likes, source: :tweet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def index
        @user = User.all
        @tweets = Tweet.all        
    end
    def create
        tweet = Tweet.find(params[:tweet_id])
        user = User.find_by(uid: session[:login_uid])
        user.like_tweets << tweet
        redirect_to '/top/main'
    end
    
    def destroy
        tweet = Tweet.find(params[:id])
        user = User.find_by(uid: session[:login_uid])        
        tweet.likes.find_by(user_id: user.id).destroy      
        redirect_to '/top/main'
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        if session[:login_uid] == nil then
            render 'login'
        else
            @tweets = Tweet.all
            render 'main'
        end
        
    end
    
    def login
     if user = User.find_by_uid(params[:uid])
        uid = params[:uid]
        pass = params[:pass]
        if uid == user.uid && BCrypt::Password.new(user.pass) ==  pass then
            session[:login_uid] = user.uid
            
            redirect_to '/top/main'
        else
            render 'error'
        end
     end
    end

    def logout
        session.delete(:login_uid)
        redirect_to '/'
    end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    protect_from_forgery except: :search # searchアクションを除外
    def index
        @tweets = Tweet.all
    end
    def new
     @tweet = Tweet.new
    end
    def create
     user = User.find_by(uid: session[:login_uid])
     message= params[:tweet][:message]
     @tweet = Tweet.new(message: message,user_id:user.id)
     if @tweet.save
       flash[:notice] = "1 record added"
       redirect_to root_path
     else
       render 'new'
     end
    end

    def show
     @tweet = Tweet.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @user = User.all
        @tweets = Tweet.all
    end
    
    def new
        @user = User.new
    end
    
    def create
        signup_pass = BCrypt::Password.create(params[:pass])
        @user = User.new(uid: params[:uid], pass: signup_pass)
        @user.save
        redirect_to '/'
    end
    
    def destroy
        user = User.find(params[:id])
        user.destroy
        redirect_to '/'
    end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/_show.html.erb
% @tweets.each do |tweet| %>
<hr>
<p>
    <%= tweet.message %>
</p>
<hr>
<% end %>

app/views/top/error.html.erb
<p>ログイン失敗</p>
<%= link_to 'Back', "/" %>

app/views/top/login.html.erb
<%= form_tag '/top/login',method: :post do %>
 <%= label_tag :uid, 'ユーザー名' %>
 <%= text_field_tag :uid %>
 <%= label_tag :pass, 'パスワード'%>
 <%= password_field_tag :pass %>
 <%= submit_tag 'ログイン' %>
<% end %>
<%= link_to 'Back', '/' %>

app/views/top/main.html.erb
<p><%= "#{session[:login_uid]}はログイン中です"%></p>

<%= link_to 'ログアウト','../top/logout' %>
<p><%= link_to'ツイート','../tweets/new' %></p>

<% @tweets.each do |e| %>
<hr>
<p>
    <%= e.message %>
    <%= link_to 'いいね',likes_path(tweet_id: e.id), method: :post %>
    <%= link_to 'いいね削除',like_path(e),method: :delete %>
</p>
<hr>
<% end %>

app/views/tweets/_form.html.erb
 <p>
  <%= f.label :message, 'message' %>
  <p><%= f.text_area :message ,size: "25x7"%></p>
 
 </p>
 <%= f.submit 'submit' %>

app/views/tweets/_show.html.erb
<% @tweets.each do |tweet| %>
<hr>
<p>
    <%= tweet.message %>
</p>
<hr>
<% end %>

app/views/tweets/new.html.erb
<p>
 <%= form_for @tweet , name: {action: :create} do |f| %>
 <%= render "form" ,f:f%>
 <p><%= link_to 'Back', '/top/main' %></p>
<% end %>
</p>

app/views/users/_show.html.erb
<% @tweets.each do |tweet| %>
<hr>
<p>
    <%= tweet.message %>
</p>
<hr>
<% end %>

app/views/users/index.html.erb
<%= link_to 'ユーザー登録','users/new' %>
<%= link_to 'ログイン','top/login' %>

<% @tweets.each do |tweet| %>
<hr>
<p>
    <%= tweet.message %>
</p>
<hr>
<% end %>

app/views/users/new.html.erb
<%= form_tag @user , url:{action: :create} do |f| %>
 <p>ユーザー登録</p>
 <%= label_tag :uid, 'ユーザー名' %>
 <%= text_field_tag :uid %>
 <%= label_tag :pass, 'パスワード'%>
 <%= password_field_tag :pass %>
 <%= submit_tag 'サインアップ' %>
<% end %>